
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  mail:
    host: smtp.naver.com #smtp 서버 주소
    port: 465 # 메일 인증서버 포트
    username: hyunsu_sim@naver.com #네이버 아이디
    password: Qr!556423! #네이버 비밀번호
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
          connectiontimeout: 600*1000
          ssl:
            trust: smtp.naver.com
            enable: true

  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 6379
    host: 127.0.0.1

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/hair?serverTimezone=Asia/Seoul
    username: hair
    password: 1234

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #entity? ?? ? ? ???? ?? ? ?? ??? db? ?????
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true

    jackson:
      serialization:
        fail-on-empty-beans: false


EMAIL_SEND_INFO :
  adminEmail : hyunsu_sim@naver.com
  adminEmailPassword : Qr!556423!
